version: '3.8'

services:
  mysqldb:
    image: mysql:8.1.0
    container_name: book-store-mysqldb
    restart: on-failure
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_DB_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_DB_USER
      MYSQL_PASSWORD: $MYSQL_DB_PASSWORD
      MYSQL_DB: $MYSQL_DATABASE
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
  app:
    depends_on:
      - mysqldb
    restart: on-failure
    image: dyatlyuk/book-store
    build: .
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - $DEBUG_PORT:$DEBUG_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://mysqldb:$MYSQL_DOCKER_PORT/$MYSQL_DATABASE",
        "spring.datasource.username" : "$MYSQL_DB_USER",
        "spring.datasource.password" : "$MYSQL_DB_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
        "spring.datasource.driver-class-name" : "com.mysql.cj.jdbc.Driver",
        "spring.jpa.hibernate.ddl-auto" : "validate"
      }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
